package loans.persistance.model;

public enum CompanyType {
    LTD,
    PUBLIC_LIMITED_COMPANY,
    LIMITED_PARTNERSHIP,
    UNLIMITED_PARTNERSHIP,
    CHARTERED_COMPANY,
    STATUTORY_COMPANY,
    HOLDING_COMPANY,
    SUBSIDIARY_COMPANY,
    SOLE_PROPRIETORSHIP,
    NON_GOVERNMENTAL_GRGANIZATION;
}
